# Generated by Django 3.1 on 2022-02-13 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomNoeud', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('valeur', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicroControleur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMicrocontroleur', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('esp32', 'ESP32')], default='ESP32', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Vanne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomNoeud', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomChamp', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('modifier_le', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
