# Generated by Django 3.1 on 2022-03-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanneGestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champ',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vannes',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vannes',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
