# Generated by Django 3.1 on 2022-03-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanneGestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanne',
            name='debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vanne',
            name='fin',
            field=models.DateTimeField(),
        ),
    ]
