# Generated by Django 3.1 on 2022-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='telephones',
            field=models.ManyToManyField(null=True, to='users.Telephone'),
        ),
    ]
